# Generated by Django 4.0.4 on 2022-08-07 03:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wodakaryalaya', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='birth',
            name='desc',
        ),
        migrations.AddField(
            model_name='birth',
            name='birthday',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='birth',
            name='city',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='birth',
            name='district',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='birth',
            name='fathername',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='birth',
            name='marriageId',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='birth',
            name='mothername',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='birth',
            name='provience',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
