# Generated by Django 4.0.4 on 2022-08-08 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wodakaryalaya', '0002_remove_birth_desc_birth_birthday_birth_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='birth',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
